cart/urls.py
from . import views
from django.urls import path

app_name = 'cart'
urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

shopapp/urls.py
from . import views
from django.urls import path

app_name = 'shopapp'
urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('slug/<slug:c_slug>/', views.allProdCat, name='products_by_cat'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='proCatdetail'),

]

shopproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopapp.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

search_app/views.py
from django.shortcuts import render
from shopapp.models import Product
from django.db.models import Q


# Create your views here.
def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request, 'search.html', {'query': query, 'products': products})

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        Cart page
{% endblock %}
{% block title %}
    Cart - K Shop
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your Shopping cart is empty</h1>
        <br>
        <p class="text-center">
            Please click <a href="{% url 'shopapp:allProdCat'  %}">Here</a> to continue shopping
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your Shopping Cart</h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_table_head">
            <tr>
                <th colspan="5"> Your items </th>
            </tr>
            </thead>
            <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="{{cart_item.product.get_url}}"><img src="{{cart_item.product.image.url}}" alt="" class=" float-left rounded custom_image" width="100px " height="150px"></a>
                    </td>
                    <td class="text-left">
                        {{cart_item.product.name}}
                        <br>
                        SKU: {{cart_item.product.id}}
                        <br>
                        Price:  ₹{{cart_item.product.price}}
                        <br>
                        Qty: {{cart_item.quantity}} x ₹ {{cart_item.product.name}}
                    </td>
                    <td>
                        ₹ {{cart_item.Sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-square-plus"></i></a>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-square-minus"></i></a>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash"></i></a>
                    </td>
                    {% else %}
                    <td>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-square-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-trash custom_icon"></i></a>
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_table_head">
            <tr>
                <th colspan="5"> Checkouts </th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                       Please review your cart items before proceeding with the order payment
                    </td>
                </tr>
            <tr>
                <td class="text-left">
                    Your Total is : ₹ <strong>{{ total }}</strong>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'shopapp:allProdCat' %}" class="btn btn-warning btn-block my_custom_button">Continue Shopping</a>
            <a href="{% url 'shopapp:allProdCat' %}" class="btn btn-success btn-block my_custom_button">Payment Options</a>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}


#cart_item.product.get_absolute_url

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description| truncatewords:155}}
    {% else %}
        Welcome to K-Shop, where Kerala shops
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name}}- K-Shop
    {% else %}
        See our new collections
    {% endif %}
{% endblock %}
{% block content %}
<div >
    {% if category %}
    <div class="row my_row">
        <div class="mx-auto">
            <p class="my_title cat_link">
                <a  href="{% url 'shopapp:allProdCat' %}"> Our product collections</a>
            </p>
        </div>
    </div>
    {% endif %}
    <div class="mx-auto">
        {% if category %}
        <img class="my_image" src="{{ category.image.url }}" alt="{{ category.name}}">
    </div><br>
    <div>
        <h1 class="text-center my_title" style="color:#002B5B; padding-top:2em;font-size:20px;"><b>{{category.name}}</b></h1>
        <p class="text-justify my_title" style="margin-left:5em;color:#002B5B; padding-bottom:2em;padding-top:2em;">{{ category.description }}</p>
    </div>
    {% else %}
    <div class="container">
        <div class="row">
<!--            <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="Our Products" width="100% " height="500px">-->

<!--            trying video banner-->
            <video autoplay muted loop id="myVideo">
                <source src="{% static 'img/banner.mp4' %}" type="video/mp4">
            </video>


        </div><br>
        <div>
            <div>
                <h1 class="text-center my_title">Our Product Collections</h1>
                <p class="text-justify">The K Shop Group is one of India's leading digital commerce entities and includes many branded products which is clearly on a affordable rate so that all of us can have our desired products. Keep shopping with us and keep investing on right hands.</p>
            </div>
        </div></br>
        {% endif %}
        <div class="container">
            <div class="row mx-auto">
                {% for product in products %}
                <div class="my_bottom_margin col-lg-4 md-4">
                    <div class="card text-center h-100"  style="width: 18rem;">

                            <a href="{{product.get_url}}"><img class=" card-img-top my_image" src="{{ product.image.url }}" alt="{{product.name}}" ></a>
                            <div class="card-body">
                                <h4>{{product.name}}</h4>
                                <p><b>₹{{product.price}}</b></p>
                            </div>

                    </div>
                </div>

                {% endfor %}
            </div>
            <div class="mx-auto">
                {% if products.paginator.num_pages > 1 %}
                <hr>
                <div class="text-center">
                    {% for pg in products.paginator.page_range %}
                    <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                    {% endfor %}
                </div>
                {% endif %}
            </div><br>
        </div>
    </div>
</div>
{% endblock %}